[package]
name = "stremio-service"
version = "0.1.0"
edition = "2021"
authors = ["Stremio"]
description = "Freedom to Stream"
license = "MIT"
homepage = "https://stremio.com"
repository = "https://github.com/Stremio/stremio-service/"
readme = "README.md"
build = "build.rs"

[[bin]]
name = "service"
path = "src/service/main.rs"

[[bin]]
name = "updater"
path = "src/updater/main.rs"

[dependencies]
clap = { version = "4.0.22", features = ["derive"] }
dirs = "4.0.0"
env_logger = "0.9.3"
image = "0.24.4"
log = "0.4.17"
octocrab = "0.17.0"
open = "3.0.3"
reqwest = "0.11.12"
rust-embed = "6.4.2"
semver = "1.0.14"
tao = { version = "0.15.3", features = ["tray"] }
tokio = { version = "1.21.2", features = ["full"] }
zip-extract = "0.1.1"

[target.'cfg(windows)'.build-dependencies]
embed-resource = "1.7.4"

[profile.release]
opt-level = 3
lto = true
strip = "debuginfo"

[package.metadata.deb]
copyright = "© 2022 Smart Code OOD"
extended-description = "Media Center"
depends = "$auto"
section = "Stremio;Media;Play;"
priority = "optional"
assets = [
    ["target/release/service", "/usr/bin/stremio-service/service", "755"],
    ["target/release/version", "/usr/bin/stremio-service/version", "755"],
    ["target/release/node", "/usr/bin/stremio-service/node", "755"],
    ["target/release/ffmpeg", "/usr/bin/stremio-service/ffmpeg", "755"],
    ["resources/stremio.service", "/etc/systemd/system/stremio.service", "644"],
    ["resources/com.stremio.service.desktop", "/usr/share/applications/com.stremio.service.desktop", "644"],
    ["resources/com.stremio.service.svg", "/usr/share/icons/hicolor/scalable/apps/com.stremio.service.svg", "644"],
]

[package.metadata.generate-rpm]
# post_install_script = "gnome_version=$(gnome-shell --version  | awk '{print $NF}') && echo https://extensions.gnome.org/extension-data/appindicatorsupportrgcjonas.gmail.com.GNOME_VERSION.shell-extension.zip | sed -e s/GNOME_VERSION/$gnome_version/g"
assets = [
    { source = "target/release/service", dest = "/usr/bin/stremio-service/service", mode = "755" },
    { source = "target/release/version", dest = "/usr/bin/stremio-service/version", mode = "755" },
    { source = "target/release/node", dest = "/usr/bin/stremio-service/node", mode = "755" },
    { source = "target/release/ffmpeg", dest = "/usr/bin/stremio-service/ffmpeg", mode = "755" },
    { source = "resources/stremio.service", dest = "/etc/systemd/system/stremio.service", mode = "644" },
    { source = "resources/com.stremio.service.desktop", dest = "/usr/share/applications/com.stremio.service.desktop", mode = "644" },
    { source = "resources/com.stremio.service.svg", dest = "/usr/share/icons/hicolor/scalable/apps/com.stremio.service.svg", mode = "644" },
]

[package.metadata.generate-rpm.requires]
libappindicator-gtk3 = "*"
