name: Linux Release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev pkg-config libssl-dev libayatana-appindicator3-dev
          cargo install cargo-deb
      - name: Build
        run: cargo build --release
      - name: Build deb
        run: cargo deb
      - name: Upload deb release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/debian/*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true