name: Linux Release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev pkg-config libssl-dev libayatana-appindicator3-dev
          cargo install cargo-deb
          cargo install cargo-generate-rpm
      - name: Get current date
        id: date
        run: echo "TODAY_DATE=$(date +'%d %b %Y')" >> $GITHUB_OUTPUT
      # Builds the deb linux package
      - name: Build deb package
        run: cargo deb
      - name: Upload deb release
        uses: softprops/action-gh-release@v1
        with:
          # Use the same name as all releases!
          name: Stremio Service ${{ github.ref_name }} (${{ steps.date.outputs.TODAY_DATE }})
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            target/debian/*.deb
      # Builds the rpm linux package
      - name: Build release
        run: cargo build --release --features=bundled
      - name: Strip debug symbols
        run: strip -s target/release/stremio-service
      - name: Build rpm package
        run: cargo generate-rpm
      - name: Upload rpm to release
        uses: softprops/action-gh-release@v1
        with:
          # Use the same name as all releases!
          name: Stremio Service ${{ github.ref_name }} (${{ steps.date.outputs.TODAY_DATE }})
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            target/generate-rpm/*.rpm
