name: MacOS Release

on:
  push:
    tags:
      - 'v*'

jobs:
  macos-release:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Homebrew setup
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Utils
        run: npm install -g create-dmg && brew install graphicsmagick imagemagick
      - name: Build
        run: cargo build --release --features=bundled
      - name: Package
        run: cargo run --bin bundle-macos && create-dmg --overwrite target/macos/*.app target/macos 2> /dev/null
      - name: Upload dmg release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/macos/*.dmg
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
      - name: Rename ffmpeg
        run: mv resources/bin/ffmpeg-macos resources/bin/ffmpeg
      - name: Zip release for macos
        uses: vimtor/action-zip@v1
        with:
          # todo: add license
          files: resources/bin/ffmpeg resources/bin/node target/release/stremio-service resources/bin/server.js
          dest: stremio-service-macos.zip
      - name: Upload zip release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: stremio-service-macos.zip
          asset_name: stremio-service-macos.zip
          tag: ${{ github.ref }}
          overwrite: true