name: Windows Release

on:
  push:
    tags:
      - 'v*'

jobs:
  windows-release:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --release
      - name: Zip release for windows
        uses: vimtor/action-zip@v1
        with:
          files: target/release/ffmpeg.exe target/release/node.exe target/release/service.exe target/release/server.js
          dest: stremio-service-windows.zip
      - name: Installer
        run: |
          & 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' 'setup\StremioService.iss'

      - name: Upload to Amazon S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: 'eu-west-1'
          AWS_S3_BUCKET: stremio-artifacts
          SOURCE_DIR: 'StremioService.exe'
          DEST_DIR: stremio-service/${{ github.ref_name }}

      - name: Upload windows release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: stremio-service-windows.zip
          asset_name: stremio-service-windows.zip
          tag: ${{ github.ref }}
          overwrite: true
